version: '3'

services:
  analyzer:
    build: ./
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ${METRICS_DIR}:/metrics
